# Generated by Django 4.0.5 on 2022-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=64)),
                ('order', models.CharField(max_length=32)),
                ('suborder', models.CharField(max_length=32)),
                ('habitat', models.CharField(max_length=64)),
                ('diet', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
