# Generated by Django 4.0.5 on 2022-06-17 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('species_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='suborder',
            new_name='genus',
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
